"""
Momentum analyzer component.

SOLID Principles:
- SRP: Only analyzes momentum data
- OCP: Extensible through new analysis methods
- LSP: Implements MomentumAnalyzer protocol
- ISP: Focused on analysis operations
- DIP: Depends on IndicatorCalculator and PriceDataProvider protocols
"""

import logging
from typing import List

import numpy as np

from app.domain.models.momentum import (
    MomentumAnalysis,
    MomentumSignal,
    TechnicalIndicators,
    Timeframe,
)
from app.services.momentum.protocols import IndicatorCalculator, PriceDataProvider

logger = logging.getLogger(__name__)


class MomentumAnalyzer:
    """
    Core momentum analysis logic.

    Single Responsibility:
    - Analyzes momentum data
    - Calculates momentum metrics
    - Assesses risk and volatility

    Dependency Inversion:
    - Depends on IndicatorCalculator protocol
    - Depends on PriceDataProvider protocol
    """

    def __init__(
        self,
        indicator_calculator: IndicatorCalculator,
        price_data_provider: PriceDataProvider,
    ) -> None:
        """
        Initialize analyzer with dependencies.

        Args:
            indicator_calculator: Calculator for technical indicators
            price_data_provider: Provider for price data
        """
        self.indicator_calculator = indicator_calculator
        self.price_data_provider = price_data_provider

    async def analyze_asset_momentum(
        self, symbol: str, timeframe: Timeframe = Timeframe.DAILY
    ) -> MomentumAnalysis:
        """
        Analyze momentum for a specific asset.

        Args:
            symbol: Asset symbol to analyze
            timeframe: Analysis timeframe (default DAILY)

        Returns:
            MomentumAnalysis object with complete analysis

        Raises:
            ValueError: If symbol is invalid or data insufficient
            KeyError: If required data is missing
        """
        try:
            price_data = await self.price_data_provider.get_price_data(symbol, timeframe)
            indicators = self.indicator_calculator.calculate_all_indicators(
                symbol,
                price_data["prices"],
                price_data["highs"],
                price_data["lows"],
                price_data["volumes"],
            )

            # Create placeholder signals (will be generated by SignalGenerator)
            signals: List[MomentumSignal] = []

            overall_momentum = self.calculate_overall_momentum(signals)
            trend_direction = self.determine_trend_direction(indicators)
            risk_level = self.assess_risk_level(indicators, signals)
            volatility_level = self.assess_volatility_level(indicators)

            analysis = MomentumAnalysis(
                symbol=symbol,
                timeframe=timeframe,
                indicators=indicators,
                signals=signals,
                overall_momentum=overall_momentum,
                trend_direction=trend_direction,
                signal_count=len(signals),
                risk_level=risk_level,
                volatility_level=volatility_level,
            )

            return analysis

        except (ValueError, KeyError, AttributeError, IndexError, TypeError) as e:
            logger.error(f"Error analyzing momentum for {symbol}: {e}")
            raise

    def calculate_overall_momentum(self, signals: List[MomentumSignal]) -> float:
        """
        Calculate overall momentum score from signals.

        Args:
            signals: List of momentum signals

        Returns:
            Overall momentum score (0-100)
        """
        if not signals:
            return 0.0

        total_score = 0.0
        total_weight = 0.0

        for signal in signals:
            weight = (signal.strength + signal.confidence) / 2
            total_score += signal.momentum_score * weight
            total_weight += weight

        return total_score / total_weight if total_weight > 0 else 0.0

    def determine_trend_direction(self, indicators: TechnicalIndicators) -> str:
        """
        Determine trend direction from indicators.

        Args:
            indicators: Technical indicators object

        Returns:
            Trend direction: "BULLISH", "BEARISH", or "NEUTRAL"
        """
        if not indicators.ema_trend:
            return "NEUTRAL"
        return indicators.ema_trend

    def assess_risk_level(
        self, indicators: TechnicalIndicators, signals: List[MomentumSignal]
    ) -> str:
        """
        Assess risk level based on indicators and signals.

        Args:
            indicators: Technical indicators
            signals: List of momentum signals

        Returns:
            Risk level: "HIGH", "MEDIUM", or "LOW"
        """
        risk_score = 0

        if indicators.volatility:
            if indicators.volatility > 5:
                risk_score += 3
            elif indicators.volatility > 3:
                risk_score += 2
            else:
                risk_score += 1

        if signals:
            avg_strength = np.mean([s.strength for s in signals])
            if avg_strength > 80:
                risk_score += 2
            elif avg_strength > 60:
                risk_score += 1

        if indicators.atr:
            if indicators.atr > 3:
                risk_score += 2
            elif indicators.atr > 1.5:
                risk_score += 1

        if risk_score >= 5:
            return "HIGH"
        elif risk_score >= 3:
            return "MEDIUM"
        else:
            return "LOW"

    def assess_volatility_level(self, indicators: TechnicalIndicators) -> str:
        """
        Assess volatility level from indicators.

        Args:
            indicators: Technical indicators

        Returns:
            Volatility level: "HIGH", "MEDIUM", or "LOW"
        """
        if not indicators.volatility:
            return "MEDIUM"

        if indicators.volatility > 5:
            return "HIGH"
        elif indicators.volatility > 2:
            return "MEDIUM"
        else:
            return "LOW"
