"""
PHASE 0 - Learning Capital Gate (T0.2.1)

Prevents learning engine initialization on small accounts where the computational
cost of learning exceeds the alpha generated by learning-driven improvements.

Economics principle: Learning has implicit costs:
- Feature extraction and preprocessing
- Model training (compute, memory, time)
- Model retraining (regular updates)
- Hyperparameter search and optimization

These costs are especially problematic on small accounts (<$25k) where:
- Cost of learning > alpha generated by learning
- Better to use simple, deterministic strategies
- Capital is better deployed with trading rather than learning infrastructure

This gate enforces:
1. Minimum capital threshold ($25k) for learning to be economically viable
2. Learning cost-benefit ratio (learning cost must be <30% of expected alpha)
3. Capital-aware learning configuration (adjusts learning frequency by account size)
4. Explicit warning when learning is disabled
"""

import logging
from decimal import Decimal
from typing import Dict, Tuple

logger = logging.getLogger(__name__)


class LearningCapitalGate:
    """
    Validates that learning engines are economically viable for the account capital.

    Prevents systematic capital loss from learning infrastructure costs that exceed
    the value generated by learning-driven strategy improvements.

    This is especially critical for small accounts where fixed learning costs
    (model training, retraining cycles) are large relative to account size.
    """

    # Economic parameters for learning viability
    MIN_CAPITAL_FOR_LEARNING = Decimal("25000")  # $25k minimum for profitable learning
    LEARNING_COST_PER_MONTH = Decimal("50")  # Estimated monthly learning cost in dollars
    MAX_LEARNING_COST_RATIO = Decimal("0.30")  # Cost can be max 30% of expected alpha

    # Alternative cost models for different account sizes
    LEARNING_COST_SCALE = {
        # (min_capital, learning_cost_pct_of_capital)
        # For micro: 0.5% = $50 on $10k account = very high
        "micro": Decimal("0.005"),  # 0.5% of capital
        "small": Decimal("0.003"),  # 0.3% of capital
        "medium": Decimal("0.002"),  # 0.2% of capital
        "large": Decimal("0.001"),  # 0.1% of capital
    }

    @staticmethod
    def is_learning_viable(
        capital: Decimal,
        expected_monthly_alpha: Decimal = Decimal("100"),
        monthly_win_rate: Decimal = Decimal("0.55"),  # 55% win rate (achievable)
        learning_enabled: bool = True,
    ) -> Tuple[bool, Dict]:
        """
        Determine if learning engine should be enabled for this account.

        Args:
            capital: Account capital in dollars
            expected_monthly_alpha: Expected monthly alpha from strategy
            monthly_win_rate: Expected win rate (55% = achievable, 60%+ = optimistic)
            learning_enabled: Whether learning is configured to be enabled

        Returns:
            (should_enable_learning: bool, analysis: Dict)

        Dict contains:
            - learning_recommended: bool - Whether learning should be enabled
            - reason: str - Human-readable explanation
            - recommendation: str - ENABLE_LEARNING | DISABLE_LEARNING | CONFIGURE_FOR_TIER
            - severity: str - OK | WARNING | CRITICAL
            - capital_tier: str - micro | small | medium | large
            - learning_cost_monthly: Decimal - Estimated monthly cost
            - cost_benefit_ratio: Decimal - Cost as % of alpha
            - minimum_capital_required: Decimal - Capital needed for learning viability
        """

        # Validate inputs
        if capital <= Decimal("0"):
            return False, {
                "learning_recommended": False,
                "reason": "Capital must be positive",
                "recommendation": "INCREASE_CAPITAL",
                "severity": "CRITICAL",
                "capital_tier": "invalid",
                "learning_cost_monthly": Decimal("0"),
                "cost_benefit_ratio": Decimal("999"),
                "minimum_capital_required": LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING,
            }

        if not learning_enabled:
            return False, {
                "learning_recommended": False,
                "reason": "Learning is not enabled in configuration",
                "recommendation": "LEARNING_DISABLED",
                "severity": "OK",
                "capital_tier": LearningCapitalGate._get_capital_tier(capital),
                "learning_cost_monthly": Decimal("0"),
                "cost_benefit_ratio": Decimal("0"),
                "minimum_capital_required": LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING,
            }

        # === CALCULATE LEARNING COST ===

        capital_tier = LearningCapitalGate._get_capital_tier(capital)

        # Use scaled learning cost based on capital size
        learning_cost_pct = LearningCapitalGate.LEARNING_COST_SCALE.get(
            capital_tier, Decimal("0.005")
        )
        learning_cost_monthly = capital * learning_cost_pct

        # === CALCULATE COST-BENEFIT RATIO ===

        if expected_monthly_alpha <= Decimal("0"):
            # No positive alpha - learning doesn't help
            cost_ratio = Decimal("999")
            learning_viable = False
            reason = (
                f"Expected monthly alpha ${expected_monthly_alpha:.2f} is not positive; "
                "learning cannot improve negative returns"
            )
            recommendation = "DISABLE_LEARNING"
            severity = "CRITICAL"
        else:
            cost_ratio = learning_cost_monthly / expected_monthly_alpha

            # Decision logic
            if capital < LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING:
                # Below minimum capital threshold
                learning_viable = False
                disadvantage = LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING - capital
                reason = (
                    f"Capital ${capital:,.0f} is below minimum viability threshold "
                    f"${LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING:,.0f} (shortfall: ${disadvantage:,.0f}). "
                    f"Learning infrastructure cost (${learning_cost_monthly:.2f}/mo) exceeds benefit on small accounts. "
                    "Recommend simple, deterministic strategies instead."
                )
                recommendation = "DISABLE_LEARNING"
                severity = "CRITICAL"
            elif cost_ratio > LearningCapitalGate.MAX_LEARNING_COST_RATIO:
                # Cost-benefit ratio too high
                learning_viable = False
                reason = (
                    f"Learning cost ${learning_cost_monthly:.2f}/mo ({cost_ratio:.0%} of alpha ${expected_monthly_alpha:.2f}/mo) "
                    f"exceeds acceptable threshold ({LearningCapitalGate.MAX_LEARNING_COST_RATIO:.0%}). "
                    "Cost of learning infrastructure outweighs expected benefit."
                )
                recommendation = "DISABLE_LEARNING"
                severity = "WARNING"
            else:
                # Learning is viable
                learning_viable = True
                margin = expected_monthly_alpha - learning_cost_monthly
                reason = (
                    f"Learning viable: Capital ${capital:,.0f} (${capital_tier} tier), "
                    f"learning cost ${learning_cost_monthly:.2f}/mo ({cost_ratio:.0%} of alpha). "
                    f"Net benefit after learning: ${margin:.2f}/mo. "
                    "Learning infrastructure justified."
                )
                recommendation = "ENABLE_LEARNING"
                severity = "OK"

        return learning_viable, {
            "learning_recommended": learning_viable,
            "reason": reason,
            "recommendation": recommendation,
            "severity": severity,
            "capital_tier": capital_tier,
            "learning_cost_monthly": learning_cost_monthly,
            "cost_benefit_ratio": cost_ratio,
            "minimum_capital_required": LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING,
            "expected_monthly_alpha": expected_monthly_alpha,
            "monthly_win_rate": monthly_win_rate,
        }

    @staticmethod
    def _get_capital_tier(capital: Decimal) -> str:
        """Classify capital into tiers"""
        if capital < Decimal("15000"):
            return "micro"  # < $15k
        elif capital < Decimal("50000"):
            return "small"  # $15k - $50k
        elif capital < Decimal("250000"):
            return "medium"  # $50k - $250k
        else:
            return "large"  # $250k+

    @staticmethod
    def get_recommended_learning_config(capital: Decimal) -> Dict:
        """
        Get recommended learning configuration for the given capital tier.

        Args:
            capital: Account capital

        Returns:
            Dict with recommended learning configuration
        """
        capital_tier = LearningCapitalGate._get_capital_tier(capital)

        configs = {
            "micro": {
                # Too small for learning - use deterministic strategy
                "learning_enabled": False,
                "reason": "Capital too small for profitable learning",
                "recommendation": "Increase capital to $25k+ for learning viability",
                "alternative": "Use simple momentum filters with manual optimization",
            },
            "small": {
                # Borderline - learning only if alpha is high
                "learning_enabled": capital >= LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING,
                "reason": "Small capital - learning only viable with high alpha expectations",
                "learning_config": {
                    "rebalance_frequency_days": 14,  # Slower retraining
                    "min_trades_for_retrain": 30,  # Higher threshold
                    "max_models": 2,  # Fewer models
                    "feature_extraction_frequency": "weekly",  # Less frequent
                },
            },
            "medium": {
                # Good for learning
                "learning_enabled": True,
                "reason": "Capital sufficient for learning viability",
                "learning_config": {
                    "rebalance_frequency_days": 7,  # Standard retraining
                    "min_trades_for_retrain": 20,
                    "max_models": 4,  # More model variety
                    "feature_extraction_frequency": "daily",
                },
            },
            "large": {
                # Excellent for learning - can afford sophisticated engines
                "learning_enabled": True,
                "reason": "Capital sufficient for sophisticated learning",
                "learning_config": {
                    "rebalance_frequency_days": 3,  # Frequent retraining
                    "min_trades_for_retrain": 10,  # Lower threshold
                    "max_models": 6,  # Full model portfolio
                    "feature_extraction_frequency": "every_trade",
                    "enable_ensemble_methods": True,
                    "enable_transfer_learning": True,
                },
            },
        }

        return configs.get(capital_tier, configs["micro"])

    @staticmethod
    def get_minimum_capital_for_learning(
        expected_monthly_alpha: Decimal = Decimal("100"),
        target_cost_ratio: Decimal = Decimal("0.30"),
    ) -> Decimal:
        """
        Calculate minimum capital needed for learning to be economically viable.

        Args:
            expected_monthly_alpha: Expected monthly alpha from strategy
            target_cost_ratio: Maximum acceptable cost as % of alpha (default 30%)

        Returns:
            Minimum capital required
        """
        if expected_monthly_alpha <= Decimal("0"):
            return Decimal("999999999")  # Impossible

        # Use medium-tier learning cost (0.2% of capital)
        learning_cost_scale = Decimal("0.002")

        # capital * learning_cost_scale = expected_monthly_alpha * target_cost_ratio
        # capital = (expected_monthly_alpha * target_cost_ratio) / learning_cost_scale

        min_capital = (expected_monthly_alpha * target_cost_ratio) / learning_cost_scale

        # Enforce minimum absolute threshold
        return max(min_capital, LearningCapitalGate.MIN_CAPITAL_FOR_LEARNING)

    @staticmethod
    def log_learning_decision(
        capital: Decimal,
        analysis: Dict,
        account_id: str = None,
    ) -> str:
        """Log learning capital gate decision for audit trail"""

        status = "✅ ENABLE" if analysis["learning_recommended"] else "❌ DISABLE"
        log_msg = (
            f"{status} | Capital: ${capital:,.0f} (${analysis['capital_tier']}) | "
            f"Learning Cost: ${analysis['learning_cost_monthly']:.2f}/mo | "
            f"Cost-Benefit Ratio: {analysis['cost_benefit_ratio']:.0%} | "
            f"Recommendation: {analysis['recommendation']}"
        )

        if account_id:
            log_msg = f"[{account_id}] {log_msg}"

        if analysis["learning_recommended"]:
            logger.info(log_msg)
        else:
            logger.warning(log_msg)

        logger.debug(f"Reason: {analysis['reason']}")

        return log_msg
