"""
Bollinger Bands Indicator Implementation

This module implements Bollinger Bands, a volatility-based indicator
commonly used in mean reversion and breakout strategies.

Bollinger Bands were developed by John Bollinger and are widely used
in algorithmic trading for:
- Mean reversion signals (price at upper/lower bands)
- Volatility measurement (bandwidth)
- Trend confirmation (squeeze/expansion)

This implementation follows Ernest Chan's recommendations from
"Algorithmic Trading" for proper signal generation.

Reference:
    "Algorithmic Trading" by Ernest P. Chan
    Chapter 6: Mean Reversion Strategies
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class BollingerBandsSignal:
    """Signal generated by Bollinger Bands indicator."""

    signal_type: str  # 'upper_band_touch', 'lower_band_touch', 'squeeze', 'expansion'
    price: Decimal
    upper_band: Decimal
    middle_band: Decimal
    lower_band: Decimal
    bandwidth: float  # (upper - lower) / middle
    pct_b: float  # (price - lower) / (upper - lower)
    timestamp: Any
    strength: float  # Signal strength (0-100)


@dataclass
class BollingerBandsConfig:
    """Configuration for Bollinger Bands calculation."""

    period: int = 20  # Standard period (default 20)
    num_std: float = 2.0  # Number of standard deviations (default 2.0)
    ma_type: str = "sma"  # 'sma' or 'ema'

    # Signal thresholds
    bandwidth_squeeze_threshold: float = 0.05  # 5% bandwidth = squeeze
    bandwidth_expansion_threshold: float = 0.15  # 15% bandwidth = expansion
    pct_b_overbought: float = 0.8  # %B > 0.8 = overbought
    pct_b_oversold: float = 0.2  # %B < 0.2 = oversold


class BollingerBandsIndicator:
    """
    Bollinger Bands indicator for mean reversion and volatility trading.

    This implementation provides:
    - Standard Bollinger Bands calculation
    - Bandwidth for volatility measurement
    - %B for relative position
    - Squeeze detection (low volatility)
    - Signal generation for mean reversion

    Formula:
        Middle Band = SMA(period)
        Upper Band = Middle Band + (num_std * std_dev)
        Lower Band = Middle Band - (num_std * std_dev)
        Bandwidth = (Upper - Lower) / Middle
        %B = (Price - Lower) / (Upper - Lower)
    """

    def __init__(self, config: Optional[BollingerBandsConfig] = None):
        """
        Initialize Bollinger Bands indicator.

        Args:
            config: Configuration for Bollinger Bands calculation
        """
        self.config = config or BollingerBandsConfig()
        logger.info(
            f"BollingerBandsIndicator initialized: period={self.config.period}, "
            f"num_std={self.config.num_std}, ma_type={self.config.ma_type}"
        )

    def calculate(
        self, prices: pd.Series, timestamps: Optional[pd.DatetimeIndex] = None
    ) -> pd.DataFrame:
        """
        Calculate Bollinger Bands for a price series.

        Args:
            prices: Series of prices
            timestamps: Optional datetime index for prices

        Returns:
            DataFrame with columns: upper, middle, lower, bandwidth, pct_b
        """
        try:
            if len(prices) < self.config.period:
                logger.warning(
                    f"Insufficient data for Bollinger Bands: "
                    f"{len(prices)} < {self.config.period}"
                )
                return self._create_empty_result(len(prices))

            # Calculate middle band (moving average)
            if self.config.ma_type == "sma":
                middle_band = prices.rolling(window=self.config.period).mean()
            else:  # ema
                middle_band = prices.ewm(span=self.config.period).mean()

            # Calculate standard deviation
            std_dev = prices.rolling(window=self.config.period).std()

            # Calculate upper and lower bands
            upper_band = middle_band + (self.config.num_std * std_dev)
            lower_band = middle_band - (self.config.num_std * std_dev)

            # Calculate bandwidth
            bandwidth = (upper_band - lower_band) / middle_band

            # Calculate %B (percent B)
            # %B shows where price is relative to the bands (0-1 range, can exceed)
            pct_b = (prices - lower_band) / (upper_band - lower_band)

            result = pd.DataFrame(
                {
                    "upper": upper_band,
                    "middle": middle_band,
                    "lower": lower_band,
                    "bandwidth": bandwidth,
                    "pct_b": pct_b,
                }
            )

            if timestamps is not None:
                result.index = timestamps

            return result

        except (ValueError, TypeError, KeyError) as e:
            logger.error(f"Error calculating Bollinger Bands: {e}")
            return self._create_empty_result(len(prices))

    def generate_signals(
        self,
        prices: pd.Series,
        timestamps: Optional[pd.DatetimeIndex] = None,
    ) -> List[BollingerBandsSignal]:
        """
        Generate trading signals based on Bollinger Bands.

        Signal Types (per Ernest Chan's methodology):
        1. Upper Band Touch: Price at/near upper band (potential short/mean reversion)
        2. Lower Band Touch: Price at/near lower band (potential long/mean reversion)
        3. Squeeze: Low bandwidth (potential breakout coming)
        4. Expansion: High bandwidth (volatility increase)

        Args:
            prices: Series of prices
            timestamps: Optional datetime index

        Returns:
            List of BollingerBandsSignal objects
        """
        try:
            bb_data = self.calculate(prices, timestamps)
            signals = []

            # Generate signals for each data point
            for i in range(len(prices)):
                if pd.isna(bb_data.iloc[i]["upper"]):
                    continue  # Skip insufficient data points

                price = Decimal(str(prices.iloc[i]))
                upper = Decimal(str(bb_data.iloc[i]["upper"]))
                middle = Decimal(str(bb_data.iloc[i]["middle"]))
                lower = Decimal(str(bb_data.iloc[i]["lower"]))
                bandwidth = float(bb_data.iloc[i]["bandwidth"])
                pct_b = float(bb_data.iloc[i]["pct_b"])

                timestamp = timestamps[i] if timestamps is not None else i

                # Detect signal type
                signal_type = None
                strength = 0.0

                # Mean reversion signals (price at bands)
                if pct_b >= self.config.pct_b_overbought:
                    signal_type = "upper_band_touch"
                    strength = min(100, (pct_b - self.config.pct_b_overbought) * 100)
                elif pct_b <= self.config.pct_b_oversold:
                    signal_type = "lower_band_touch"
                    strength = min(100, (self.config.pct_b_oversold - pct_b) * 100)

                # Volatility signals
                elif bandwidth <= self.config.bandwidth_squeeze_threshold:
                    signal_type = "squeeze"
                    strength = (self.config.bandwidth_squeeze_threshold - bandwidth) * 100
                elif bandwidth >= self.config.bandwidth_expansion_threshold:
                    signal_type = "expansion"
                    strength = (bandwidth - self.config.bandwidth_expansion_threshold) * 100

                if signal_type:
                    signal = BollingerBandsSignal(
                        signal_type=signal_type,
                        price=price,
                        upper_band=upper,
                        middle_band=middle,
                        lower_band=lower,
                        bandwidth=bandwidth,
                        pct_b=pct_b,
                        timestamp=timestamp,
                        strength=strength,
                    )
                    signals.append(signal)

            logger.info(f"Generated {len(signals)} Bollinger Bands signals")
            return signals

        except (ValueError, TypeError, KeyError) as e:
            logger.error(f"Error generating Bollinger Bands signals: {e}")
            return []

    def is_mean_reversion_buy(
        self,
        current_price: Decimal,
        bb_data: pd.DataFrame,
        lookback: int = 1,
    ) -> bool:
        """
        Check if current conditions indicate a mean reversion buy signal.

        Per Ernest Chan: Buy when price touches lower band and shows
        signs of reversal (starts moving back toward middle).

        Args:
            current_price: Current market price
            bb_data: DataFrame with Bollinger Bands data
            lookback: Number of periods to look back for reversal

        Returns:
            True if mean reversion buy signal detected
        """
        try:
            if len(bb_data) < lookback + 1:
                return False

            current = bb_data.iloc[-1]
            previous = bb_data.iloc[-lookback - 1]

            # Price should be at or below lower band
            price_at_lower = float(current_price) <= float(current["lower"]) * 1.01

            # Price should be moving back toward middle band
            moving_to_middle = (
                float(previous["pct_b"]) < float(current["pct_b"])
                if not pd.isna(current["pct_b"]) and not pd.isna(previous["pct_b"])
                else False
            )

            return price_at_lower and moving_to_middle

        except (ValueError, TypeError, KeyError, IndexError) as e:
            logger.error(f"Error checking mean reversion buy: {e}")
            return False

    def is_mean_reversion_sell(
        self,
        current_price: Decimal,
        bb_data: pd.DataFrame,
        lookback: int = 1,
    ) -> bool:
        """
        Check if current conditions indicate a mean reversion sell signal.

        Per Ernest Chan: Sell when price touches upper band and shows
        signs of reversal (starts moving back toward middle).

        Args:
            current_price: Current market price
            bb_data: DataFrame with Bollinger Bands data
            lookback: Number of periods to look back for reversal

        Returns:
            True if mean reversion sell signal detected
        """
        try:
            if len(bb_data) < lookback + 1:
                return False

            current = bb_data.iloc[-1]
            previous = bb_data.iloc[-lookback - 1]

            # Price should be at or above upper band
            price_at_upper = float(current_price) >= float(current["upper"]) * 0.99

            # Price should be moving back toward middle band
            moving_to_middle = (
                float(previous["pct_b"]) > float(current["pct_b"])
                if not pd.isna(current["pct_b"]) and not pd.isna(previous["pct_b"])
                else False
            )

            return price_at_upper and moving_to_middle

        except (ValueError, TypeError, KeyError, IndexError) as e:
            logger.error(f"Error checking mean reversion sell: {e}")
            return False

    def detect_squeeze(self, bb_data: pd.DataFrame, lookback: int = 20) -> bool:
        """
        Detect Bollinger Band squeeze (low volatility period).

        Per Ernest Chan: Squeeze often precedes breakout moves.
        Detect when bandwidth is at low levels relative to recent history.

        Args:
            bb_data: DataFrame with Bollinger Bands data
            lookback: Period to compare for low bandwidth

        Returns:
            True if squeeze detected
        """
        try:
            if len(bb_data) < lookback:
                return False

            current_bandwidth = float(bb_data.iloc[-1]["bandwidth"])

            if pd.isna(current_bandwidth):
                return False

            # Check if current bandwidth is below recent minimum
            recent_bandwidth = bb_data["bandwidth"].iloc[-lookback:].dropna()
            min_bandwidth = recent_bandwidth.min()

            # Squeeze if current bandwidth is at or near recent lows
            is_squeeze = current_bandwidth <= min_bandwidth * 1.05

            return is_squeeze

        except (ValueError, TypeError, KeyError, IndexError) as e:
            logger.error(f"Error detecting squeeze: {e}")
            return False

    def calculate_bandwidth_percentile(self, bb_data: pd.DataFrame, lookback: int = 252) -> float:
        """
        Calculate the percentile rank of current bandwidth.

        Useful for identifying volatility regime: low percentile = squeeze,
        high percentile = expansion.

        Args:
            bb_data: DataFrame with Bollinger Bands data
            lookback: Period for percentile calculation

        Returns:
            Percentile rank (0-100)
        """
        try:
            if len(bb_data) < lookback:
                return 50.0  # Neutral if insufficient data

            current_bandwidth = float(bb_data.iloc[-1]["bandwidth"])

            if pd.isna(current_bandwidth):
                return 50.0

            recent_bandwidths = bb_data["bandwidth"].iloc[-lookback:].dropna()

            # Calculate percentile rank
            percentile = (
                (recent_bandwidths < current_bandwidth).mean() * 100
            )

            return percentile

        except (ValueError, TypeError, KeyError, IndexError) as e:
            logger.error(f"Error calculating bandwidth percentile: {e}")
            return 50.0

    def _create_empty_result(self, size: int) -> pd.DataFrame:
        """Create empty result DataFrame."""
        return pd.DataFrame(
            {
                "upper": [np.nan] * size,
                "middle": [np.nan] * size,
                "lower": [np.nan] * size,
                "bandwidth": [np.nan] * size,
                "pct_b": [np.nan] * size,
            }
        )


def calculate_bollinger_bands(
    prices: List[float] | pd.Series,
    period: int = 20,
    num_std: float = 2.0,
    ma_type: str = "sma",
) -> pd.DataFrame:
    """
    Convenience function to calculate Bollinger Bands.

    Args:
        prices: Price data (list or Series)
        period: Lookback period (default 20)
        num_std: Number of standard deviations (default 2.0)
        ma_type: Moving average type ('sma' or 'ema')

    Returns:
        DataFrame with Bollinger Bands data
    """
    config = BollingerBandsConfig(period=period, num_std=num_std, ma_type=ma_type)
    indicator = BollingerBandsIndicator(config)

    if isinstance(prices, list):
        prices = pd.Series(prices)

    return indicator.calculate(prices)
