"""
Signal Diagnostic Logger for Multi-Strategy Backtesting.

Tracks detailed information about signal generation, rejection reasons,
and strategy-level metrics for diagnostic purposes.
"""

import json
import logging
from collections import defaultdict
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, DefaultDict, Dict, List, Optional

logger = logging.getLogger(__name__)


class SignalDiagnosticLogger:
    """Diagnostic logger for signal generation and rejection tracking."""

    def __init__(self, output_dir: Path = Path("docs/BACKTEST_RESULTS/diagnostics")):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Strategy-level counters
        self.strategy_stats: DefaultDict[str, Dict[str, Any]] = defaultdict(
            lambda: {
                "signals_candidate": 0,  # Signals generated by strategy
                "signals_rejected_risk": 0,  # Rejected by risk check
                "signals_rejected_filter": 0,  # Rejected by sector/filter
                "signals_executed": 0,  # Successfully executed
                "checks_failed": defaultdict(int),  # Track which checks fail
            }
        )

        # Detailed rejection reasons
        self.rejection_details: List[Dict[str, Any]] = []

        # Detailed candidate signals (similar to rejections)
        self.candidate_details: List[Dict[str, Any]] = []

        # Per-symbol tracking
        self.symbol_stats: Dict[str, Dict[str, int]] = defaultdict(
            lambda: {
                "candidates": 0,
                "executed": 0,
                "rejected": 0,
            }
        )

    def log_signal_candidate(
        self,
        strategy_name: str,
        symbol: str,
        signal_type: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Log a signal candidate generated by strategy."""
        self.strategy_stats[strategy_name]["signals_candidate"] += 1
        self.symbol_stats[symbol]["candidates"] += 1

        entry = {
            "timestamp": datetime.utcnow().isoformat(),
            "strategy": strategy_name,
            "symbol": symbol,
            "signal_type": signal_type,
            "metadata": metadata or {},
        }
        self.candidate_details.append(entry)

        logger.debug(f"[{strategy_name}] Signal candidate: {symbol} {signal_type}")

    def log_signal_rejected(
        self,
        strategy_name: str,
        symbol: str,
        reason: str,
        failed_check: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Log a rejected signal with reason."""
        if "risk" in reason.lower():
            self.strategy_stats[strategy_name]["signals_rejected_risk"] += 1
        else:
            self.strategy_stats[strategy_name]["signals_rejected_filter"] += 1

        if failed_check:
            self.strategy_stats[strategy_name]["checks_failed"][failed_check] += 1

        self.symbol_stats[symbol]["rejected"] += 1

        entry = {
            "timestamp": datetime.utcnow().isoformat(),
            "strategy": strategy_name,
            "symbol": symbol,
            "reason": reason,
            "failed_check": failed_check,
            "metadata": metadata or {},
        }
        self.rejection_details.append(entry)

        logger.debug(f"[{strategy_name}] Signal rejected: {symbol} - {reason}")

    def log_signal_executed(
        self,
        strategy_name: str,
        symbol: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Log a successfully executed signal."""
        self.strategy_stats[strategy_name]["signals_executed"] += 1
        self.symbol_stats[symbol]["executed"] += 1

        logger.debug(f"[{strategy_name}] Signal executed: {symbol}")

    def get_strategy_summary(self, strategy_name: str) -> Dict[str, Any]:
        """Get summary statistics for a strategy."""
        stats = self.strategy_stats[strategy_name]
        candidates = stats["signals_candidate"]
        executed = stats["signals_executed"]
        rejected = stats["signals_rejected_risk"] + stats["signals_rejected_filter"]

        return {
            "strategy": strategy_name,
            "signals_candidate": candidates,
            "signals_executed": executed,
            "signals_rejected": rejected,
            "execution_rate": (executed / candidates * 100) if candidates > 0 else 0.0,
            "rejection_rate": (rejected / candidates * 100) if candidates > 0 else 0.0,
            "checks_failed": dict(stats["checks_failed"]),
        }

    def get_all_summaries(self) -> Dict[str, Dict[str, Any]]:
        """Get summaries for all strategies."""
        return {
            strategy: self.get_strategy_summary(strategy) for strategy in self.strategy_stats.keys()
        }

    def save_diagnostic_report(self, filename: str = None) -> Path:
        """Save diagnostic report to JSON file."""
        if filename is None:
            filename = f"signal_diagnostics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

        output_file = self.output_dir / filename

        report = {
            "generated_at": datetime.utcnow().isoformat(),
            "strategy_summaries": self.get_all_summaries(),
            "strategy_stats": {
                k: dict(v) for k, v in self.strategy_stats.items()
            },  # Include full stats
            "candidates": self.candidate_details,  # ALL candidates (not just last 1000)
            "rejection_details": self.rejection_details,  # ALL rejections (not just last 1000)
            "top_rejected_symbols": sorted(
                [{"symbol": s, **stats} for s, stats in self.symbol_stats.items()],
                key=lambda x: x["rejected"],
                reverse=True,
            )[:20],
        }

        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2, default=str)

        logger.info(f"Diagnostic report saved to {output_file}")
        return output_file

    def print_summary(self) -> None:
        """Log summary to file instead of console to avoid losing information."""
        log_lines = []
        log_lines.append("\n" + "=" * 80)
        log_lines.append("📊 DIAGNÓSTICO DE SEÑALES POR ESTRATEGIA")
        log_lines.append("=" * 80)

        for strategy, summary in self.get_all_summaries().items():
            log_lines.append(f"\n{strategy.upper()}:")
            log_lines.append(f"  Candidatas:     {summary['signals_candidate']}")
            log_lines.append(
                f"  Ejecutadas:     {summary['signals_executed']} ({summary['execution_rate']:.1f}%)"
            )
            log_lines.append(
                f"  Rechazadas:     {summary['signals_rejected']} ({summary['rejection_rate']:.1f}%)"
            )

            if summary['checks_failed']:
                log_lines.append(f"  Checks fallidos:")
                for check, count in sorted(
                    summary['checks_failed'].items(), key=lambda x: x[1], reverse=True
                ):
                    log_lines.append(f"    - {check}: {count} veces")

        log_lines.append("\n" + "=" * 80)

        # Write to logger instead of console
        summary_text = "\n".join(log_lines)
        logger.info(summary_text)

        # Also save to a separate summary log file
        summary_file = (
            self.output_dir / f"diagnostic_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
        )
        with open(summary_file, 'w') as f:
            f.write(summary_text)
        logger.info(f"Diagnostic summary saved to {summary_file}")

    def reset(self) -> None:
        """Reset all counters (for new backtest run)."""
        self.strategy_stats.clear()
        self.rejection_details.clear()
        self.candidate_details.clear()
        self.symbol_stats.clear()
