"""
Market Analysis Module

This module provides comprehensive market analysis tools including:
- Market microstructure analysis
- Order Flow Imbalance (OFI) analysis
- Price discovery mechanisms
- Liquidity analysis

Components:
-----------
- microstructure/: Market microstructure theory implementation
  - OFI: Order Flow Imbalance analysis
"""

from app.domain.market_analysis.microstructure import (
    # Order Flow
    OrderType,
    OrderSide,
    TraderType,
    Order,
    OrderFlowSnapshot,
    InformationAsymmetryMetrics,
    OrderFlowForecast,
    OrderFlowAnalyzer,
    OrderFlowSimulator,
    get_order_flow_analyzer,
    get_order_flow_simulator,
    # Liquidity
    LiquidityDimension,
    SpreadComponent,
    LiquidityMetrics,
    SpreadDecomposition,
    DepthProfile,
    LiquidityRisk,
    LiquidityAnalyzer,
    LiquidityMonitor,
    get_liquidity_analyzer,
    get_liquidity_monitor,
    # Price Discovery
    PriceDiscoveryModel,
    MarketEfficiency,
    PriceDiscoveryMetrics,
    EfficientPriceEstimate,
    InformationFlowMetrics,
    MarketIntegrationMetrics,
    PriceDiscoveryAnalyzer,
    PriceDiscoveryMonitor,
    get_price_discovery_analyzer,
    get_price_discovery_monitor,
    # Trading Mechanisms
    MarketMechanism,
    AuctionType,
    OrderPriority,
    LimitOrder,
    AuctionResult,
    DealerInventoryState,
    ExecutionQuality,
    CallAuction,
    ContinuousDoubleAuction,
    DealerMarket,
    TradingMechanismComparator,
    get_call_auction,
    get_continuous_double_auction,
    get_dealer_market,
    get_mechanism_comparator,
    # Models
    ModelType,
    InformationEvent,
    ModelParameters,
    GlostenMilgromResult,
    KyleModelResult,
    OrderFlowImpactResult,
    RollSpreadResult,
    StollDecompositionResult,
    GlostenMilgromModel,
    KyleModel,
    MadhavanRichardsonModel,
    RollSpreadEstimator,
    StollSpreadDecomposer,
    MicrostructureModelComparator,
    get_glosten_milgrom_model,
    get_kyle_model,
    get_madhavanh_richardson_model,
    get_roll_estimator,
    get_stoll_decomposer,
    get_model_comparator,
)

from app.domain.market_analysis.microstructure.ofi import (
    # OFI Models
    OrderBookSnapshot,
    TickData,
    OFIConfig,
    OFISignalConfig,
    OFIPrediction,
    OFISignal,
    CumulativeOFI,
    # OFI Classes
    OFICalculator,
    OFIPredictor,
    OFISignalGenerator,
    TickLevelOFIProcessor,
)

__all__ = [
    # Microstructure - Order Flow
    "OrderType",
    "OrderSide",
    "TraderType",
    "Order",
    "OrderFlowSnapshot",
    "InformationAsymmetryMetrics",
    "OrderFlowForecast",
    "OrderFlowAnalyzer",
    "OrderFlowSimulator",
    "get_order_flow_analyzer",
    "get_order_flow_simulator",
    # Microstructure - Liquidity
    "LiquidityDimension",
    "SpreadComponent",
    "LiquidityMetrics",
    "SpreadDecomposition",
    "DepthProfile",
    "LiquidityRisk",
    "LiquidityAnalyzer",
    "LiquidityMonitor",
    "get_liquidity_analyzer",
    "get_liquidity_monitor",
    # Microstructure - Price Discovery
    "PriceDiscoveryModel",
    "MarketEfficiency",
    "PriceDiscoveryMetrics",
    "EfficientPriceEstimate",
    "InformationFlowMetrics",
    "MarketIntegrationMetrics",
    "PriceDiscoveryAnalyzer",
    "PriceDiscoveryMonitor",
    "get_price_discovery_analyzer",
    "get_price_discovery_monitor",
    # Microstructure - Trading Mechanisms
    "MarketMechanism",
    "AuctionType",
    "OrderPriority",
    "LimitOrder",
    "AuctionResult",
    "DealerInventoryState",
    "ExecutionQuality",
    "CallAuction",
    "ContinuousDoubleAuction",
    "DealerMarket",
    "TradingMechanismComparator",
    "get_call_auction",
    "get_continuous_double_auction",
    "get_dealer_market",
    "get_mechanism_comparator",
    # Microstructure - Models
    "ModelType",
    "InformationEvent",
    "ModelParameters",
    "GlostenMilgromResult",
    "KyleModelResult",
    "OrderFlowImpactResult",
    "RollSpreadResult",
    "StollDecompositionResult",
    "GlostenMilgromModel",
    "KyleModel",
    "MadhavanRichardsonModel",
    "RollSpreadEstimator",
    "StollSpreadDecomposer",
    "MicrostructureModelComparator",
    "get_glosten_milgrom_model",
    "get_kyle_model",
    "get_madhavanh_richardson_model",
    "get_roll_estimator",
    "get_stoll_decomposer",
    "get_model_comparator",
    # OFI
    "OrderBookSnapshot",
    "TickData",
    "OFIConfig",
    "OFISignalConfig",
    "OFIPrediction",
    "OFISignal",
    "CumulativeOFI",
    "OFICalculator",
    "OFIPredictor",
    "OFISignalGenerator",
    "TickLevelOFIProcessor",
]
