"""
T8.1 RealTimeMonitor - Real-time position monitoring and breach detection

Monitors currently scaled positions and detects limit breaches in real-time.

Responsibilities:
- Monitor scaled position changes
- Detect dynamic limit breaches
- Generate adjustment alerts
- Track monitoring statistics
- Provide feedback loop for scaling adjustments
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Dict, List, Optional, Tuple

from .limit_adjuster import AdjustedLimit, LimitBreach

logger = logging.getLogger(__name__)


@dataclass
class PositionSnapshot:
    """Point-in-time position snapshot."""

    timestamp: datetime
    module_name: str
    position_value: Decimal
    limit: Decimal
    percent_of_limit: Decimal
    status: str  # "ok", "warning", "critical"


@dataclass
class MonitoringAlert:
    """Alert generated by real-time monitor."""

    alert_type: str  # "breach_detected", "recovery", "scaling_recommended", "limit_exceeded"
    severity: str  # "info", "warning", "critical"
    module_name: str
    current_position: Decimal
    adjusted_limit: Decimal
    excess_amount: Decimal
    excess_pct: Decimal
    timestamp: datetime
    message: str
    recommended_action: str


@dataclass
class MonitoringReport:
    """Real-time monitoring report."""

    monitoring_start: datetime
    monitoring_end: datetime
    positions_monitored: int
    alerts_generated: int
    breaches_detected: int
    critical_breaches: int
    recovery_count: int

    position_snapshots: List[PositionSnapshot] = field(default_factory=list)
    alerts: List[MonitoringAlert] = field(default_factory=list)

    def add_alert(self, alert: MonitoringAlert) -> None:
        """Add alert to report."""
        self.alerts.append(alert)
        self.alerts_generated += 1

        if alert.alert_type == "breach_detected":
            self.breaches_detected += 1
            if alert.severity == "critical":
                self.critical_breaches += 1
        elif alert.alert_type == "recovery":
            self.recovery_count += 1


class RealTimeMonitor:
    """
    Monitors scaled positions in real-time for limit breaches.

    Tracks position changes and generates alerts when:
    - Positions breach adjusted limits
    - Positions recover to acceptable levels
    - Scaling adjustments are recommended
    - Critical breaches occur
    """

    def __init__(self):
        """Initialize real-time monitor."""
        self.position_history: Dict[str, List[PositionSnapshot]] = {}
        self.current_positions: Dict[str, Decimal] = {}
        self.previous_positions: Dict[str, Decimal] = {}
        self.breach_state: Dict[str, str] = {}  # module_name → "ok"/"warning"/"critical"
        self.last_alert: Dict[str, MonitoringAlert] = {}  # Most recent alert per module
        logger.info("✅ RealTimeMonitor initialized")

    # ========================================================================
    # Position Monitoring
    # ========================================================================

    def update_positions(
        self,
        current_positions: Dict[str, Decimal],
        adjusted_limits: List[AdjustedLimit],
    ) -> Tuple[List[PositionSnapshot], List[MonitoringAlert]]:
        """
        Update current positions and detect changes.

        Args:
            current_positions: Current position values by module
            adjusted_limits: Adjusted limits for each module

        Returns:
            (position_snapshots, alerts_generated)
        """
        snapshots = []
        alerts = []
        timestamp = datetime.utcnow()

        # Store previous state
        self.previous_positions = self.current_positions.copy()
        self.current_positions = current_positions.copy()

        # Create snapshots for all positions
        for limit in adjusted_limits:
            position = current_positions.get(limit.module_name, Decimal("0"))

            # Calculate metrics
            if limit.adjusted_limit > Decimal("0"):
                percent_of_limit = (position / limit.adjusted_limit) * Decimal("100")
            else:
                percent_of_limit = Decimal("0")

            # Determine status
            if position <= limit.adjusted_limit * Decimal("0.8"):
                status = "ok"
            elif position <= limit.adjusted_limit:
                status = "warning"
            else:
                status = "critical"

            # Create snapshot
            snapshot = PositionSnapshot(
                timestamp=timestamp,
                module_name=limit.module_name,
                position_value=position,
                limit=limit.adjusted_limit,
                percent_of_limit=percent_of_limit,
                status=status,
            )
            snapshots.append(snapshot)

            # Add to history
            if limit.module_name not in self.position_history:
                self.position_history[limit.module_name] = []
            self.position_history[limit.module_name].append(snapshot)

            # Check for state transitions and generate alerts
            previous_status = self.breach_state.get(limit.module_name, "ok")
            self.breach_state[limit.module_name] = status

            if status != previous_status:
                alert = self._generate_transition_alert(
                    limit, position, previous_status, status, timestamp
                )
                if alert:
                    alerts.append(alert)
                    self.last_alert[limit.module_name] = alert

        if alerts:
            logger.warning(f"⚠️ Generated {len(alerts)} monitoring alerts")

        return snapshots, alerts

    # ========================================================================
    # Breach Detection
    # ========================================================================

    def detect_new_breaches(
        self,
        breaches: List[LimitBreach],
    ) -> List[MonitoringAlert]:
        """
        Detect new limit breaches compared to previous state.

        Args:
            breaches: Current limit breaches

        Returns:
            List of alerts for newly detected breaches
        """
        alerts = []
        timestamp = datetime.utcnow()

        for breach in breaches:
            # Check if this is a new breach (not in previous state)
            previous_status = self.breach_state.get(breach.module_name, "ok")

            if previous_status != "critical" and breach.severity == "critical":
                alert = MonitoringAlert(
                    alert_type="breach_detected",
                    severity="critical",
                    module_name=breach.module_name,
                    current_position=breach.current_position,
                    adjusted_limit=breach.adjusted_limit,
                    excess_amount=breach.excess,
                    excess_pct=(
                        (breach.excess / breach.adjusted_limit) * Decimal("100")
                        if breach.adjusted_limit > Decimal("0")
                        else Decimal("0")
                    ),
                    timestamp=timestamp,
                    message=f"🚨 CRITICAL BREACH: {breach.module_name} position "
                    f"(€{breach.current_position:,.0f}) exceeds limit "
                    f"(€{breach.adjusted_limit:,.0f}) by €{breach.excess:,.0f}",
                    recommended_action=breach.recommendation,
                )
                alerts.append(alert)
                self.last_alert[breach.module_name] = alert

            elif previous_status == "ok" and breach.severity == "warning":
                alert = MonitoringAlert(
                    alert_type="breach_detected",
                    severity="warning",
                    module_name=breach.module_name,
                    current_position=breach.current_position,
                    adjusted_limit=breach.adjusted_limit,
                    excess_amount=breach.excess,
                    excess_pct=(
                        (breach.excess / breach.adjusted_limit) * Decimal("100")
                        if breach.adjusted_limit > Decimal("0")
                        else Decimal("0")
                    ),
                    timestamp=timestamp,
                    message=f"⚠️ WARNING BREACH: {breach.module_name} approaching limit",
                    recommended_action=breach.recommendation,
                )
                alerts.append(alert)
                self.last_alert[breach.module_name] = alert

        return alerts

    # ========================================================================
    # Recovery Detection
    # ========================================================================

    def detect_recovery(
        self,
        current_positions: Dict[str, Decimal],
        adjusted_limits: List[AdjustedLimit],
    ) -> List[MonitoringAlert]:
        """
        Detect when positions recover from breached state.

        Args:
            current_positions: Current position values
            adjusted_limits: Adjusted limits

        Returns:
            List of recovery alerts
        """
        alerts = []
        timestamp = datetime.utcnow()

        for limit in adjusted_limits:
            position = current_positions.get(limit.module_name, Decimal("0"))
            previous_status = self.breach_state.get(limit.module_name, "ok")

            # Check if position is now within limits but was previously breached
            if position <= limit.adjusted_limit and previous_status != "ok":
                alert = MonitoringAlert(
                    alert_type="recovery",
                    severity="info",
                    module_name=limit.module_name,
                    current_position=position,
                    adjusted_limit=limit.adjusted_limit,
                    excess_amount=Decimal("0"),
                    excess_pct=Decimal("0"),
                    timestamp=timestamp,
                    message=f"✅ RECOVERY: {limit.module_name} position recovered "
                    f"to acceptable level (€{position:,.0f} / €{limit.adjusted_limit:,.0f})",
                    recommended_action="Monitor for stability",
                )
                alerts.append(alert)
                self.last_alert[limit.module_name] = alert

        return alerts

    # ========================================================================
    # Scaling Recommendations
    # ========================================================================

    def recommend_scaling_adjustment(
        self,
        breaches: List[LimitBreach],
        current_scaling_factor: Decimal,
    ) -> Optional[MonitoringAlert]:
        """
        Recommend scaling adjustment based on breach patterns.

        Args:
            breaches: Current limit breaches
            current_scaling_factor: Current risk scaling factor

        Returns:
            Alert with scaling recommendation, or None if no change needed
        """
        timestamp = datetime.utcnow()

        # Count critical breaches
        critical_count = sum(1 for b in breaches if b.severity == "critical")
        warning_count = sum(1 for b in breaches if b.severity == "warning")

        if critical_count >= 2:
            # Multiple critical breaches suggest scaling should be reduced
            recommended_factor = current_scaling_factor * Decimal("0.8")

            alert = MonitoringAlert(
                alert_type="scaling_recommended",
                severity="critical",
                module_name="portfolio",
                current_position=Decimal("0"),
                adjusted_limit=Decimal("0"),
                excess_amount=Decimal("0"),
                excess_pct=Decimal("0"),
                timestamp=timestamp,
                message=f"Recommend reducing scaling factor from {current_scaling_factor:.2f}x "
                f"to {recommended_factor:.2f}x ({critical_count} critical breaches detected)",
                recommended_action=f"Apply scaling factor: {recommended_factor:.2f}x",
            )
            return alert

        elif critical_count == 1 and warning_count >= 2:
            # Single critical + multiple warnings suggest moderate reduction
            recommended_factor = current_scaling_factor * Decimal("0.9")

            alert = MonitoringAlert(
                alert_type="scaling_recommended",
                severity="warning",
                module_name="portfolio",
                current_position=Decimal("0"),
                adjusted_limit=Decimal("0"),
                excess_amount=Decimal("0"),
                excess_pct=Decimal("0"),
                timestamp=timestamp,
                message=f"Recommend moderate scaling reduction from {current_scaling_factor:.2f}x "
                f"to {recommended_factor:.2f}x",
                recommended_action=f"Apply scaling factor: {recommended_factor:.2f}x",
            )
            return alert

        return None

    # ========================================================================
    # Monitoring Reports
    # ========================================================================

    def generate_monitoring_report(
        self,
        start_time: datetime,
        end_time: datetime,
        all_alerts: List[MonitoringAlert],
    ) -> MonitoringReport:
        """
        Generate comprehensive monitoring report.

        Args:
            start_time: Report period start
            end_time: Report period end
            all_alerts: All alerts generated during period

        Returns:
            MonitoringReport with statistics and details
        """
        report = MonitoringReport(
            monitoring_start=start_time,
            monitoring_end=end_time,
            positions_monitored=len(self.current_positions),
            alerts_generated=0,
            breaches_detected=0,
            critical_breaches=0,
            recovery_count=0,
        )

        # Add all alerts to report
        for alert in all_alerts:
            report.add_alert(alert)

        # Add position snapshots from history
        for module_name, snapshots in self.position_history.items():
            # Get snapshots in reporting period
            period_snapshots = [s for s in snapshots if start_time <= s.timestamp <= end_time]
            report.position_snapshots.extend(period_snapshots)

        logger.info(
            f"✅ Generated monitoring report: {report.alerts_generated} alerts, "
            f"{report.breaches_detected} breaches, {report.critical_breaches} critical"
        )
        return report

    # ========================================================================
    # Monitoring Statistics
    # ========================================================================

    def get_monitor_status(self) -> Dict:
        """Get current monitoring status."""
        critical_modules = [m for m, s in self.breach_state.items() if s == "critical"]
        warning_modules = [m for m, s in self.breach_state.items() if s == "warning"]

        return {
            "positions_tracked": len(self.current_positions),
            "breach_state_distribution": {
                "ok": sum(1 for s in self.breach_state.values() if s == "ok"),
                "warning": len(warning_modules),
                "critical": len(critical_modules),
            },
            "critical_modules": critical_modules,
            "warning_modules": warning_modules,
            "total_alerts_generated": sum(
                1 for alerts in [self.last_alert.values()] for a in alerts
            ),
            "last_update": datetime.utcnow().isoformat(),
        }

    # ========================================================================
    # Helper Methods
    # ========================================================================

    def _generate_transition_alert(
        self,
        limit: AdjustedLimit,
        position: Decimal,
        previous_status: str,
        current_status: str,
        timestamp: datetime,
    ) -> Optional[MonitoringAlert]:
        """Generate alert for status transition."""
        if current_status == previous_status:
            return None

        excess = position - limit.adjusted_limit
        excess_pct = (
            (excess / limit.adjusted_limit) * Decimal("100")
            if limit.adjusted_limit > Decimal("0")
            else Decimal("0")
        )

        if current_status == "critical":
            return MonitoringAlert(
                alert_type="limit_exceeded",
                severity="critical",
                module_name=limit.module_name,
                current_position=position,
                adjusted_limit=limit.adjusted_limit,
                excess_amount=max(Decimal("0"), excess),
                excess_pct=max(Decimal("0"), excess_pct),
                timestamp=timestamp,
                message=f"Position exceeded limit: €{position:,.0f} > €{limit.adjusted_limit:,.0f}",
                recommended_action="Reduce position to limit",
            )

        elif current_status == "warning" and previous_status == "ok":
            return MonitoringAlert(
                alert_type="breach_detected",
                severity="warning",
                module_name=limit.module_name,
                current_position=position,
                adjusted_limit=limit.adjusted_limit,
                excess_amount=max(Decimal("0"), excess),
                excess_pct=max(Decimal("0"), excess_pct),
                timestamp=timestamp,
                message=f"Position approaching limit: €{position:,.0f} approaching €{limit.adjusted_limit:,.0f}",
                recommended_action="Monitor position closely",
            )

        elif current_status == "ok":
            return MonitoringAlert(
                alert_type="recovery",
                severity="info",
                module_name=limit.module_name,
                current_position=position,
                adjusted_limit=limit.adjusted_limit,
                excess_amount=Decimal("0"),
                excess_pct=Decimal("0"),
                timestamp=timestamp,
                message=f"Position returned to normal: €{position:,.0f} within limit",
                recommended_action="Continue monitoring",
            )

        return None

    def reset_history(self) -> None:
        """Clear monitoring history."""
        self.position_history.clear()
        self.breach_state.clear()
        self.last_alert.clear()
        logger.info("✅ Monitoring history reset")


# Singleton instance
_monitor: Optional[RealTimeMonitor] = None


def get_realtime_monitor() -> RealTimeMonitor:
    """Get or create singleton RealTimeMonitor."""
    global _monitor
    if _monitor is None:
        pass

    return _monitor
